name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: charlesdias/nrfconnect-sdk

    steps:
    - uses: actions/checkout@v3

    - name: Build the firmware
      run: |
        make build

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Archive production artifacts
        path: |
          build/zephyr/zephyr.elf
          build/zephyr/zephyr.hex
          build/zephyr/zephyr.map
          retention-days: 90